# Generated by Django 4.0.4 on 2022-06-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_tag',
            field=models.ManyToManyField(blank=True, related_name='category', to='auctions.tag'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='post_title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
