# Generated by Django 4.0.4 on 2022-06-16 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_comment_body_alter_listing_list_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winbid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BidTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid_item', to='auctions.listing')),
                ('top_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topbid', to='auctions.bid')),
            ],
        ),
    ]
