# Generated by Django 4.0.4 on 2022-06-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_winner_bidtable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BidTable',
            new_name='BidTracker',
        ),
    ]
