# Generated by Django 4.0.4 on 2022-06-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_top_bid_delete_bidtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='top_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
